/**
 * This class is generated by jOOQ
 */
package com.hr.service;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HrdbShared extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 233480317;

	/**
	 * The singleton instance of <code>hrdb_shared</code>
	 */
	public static final HrdbShared HRDB_SHARED = new HrdbShared();

	/**
	 * No further instances allowed
	 */
	private HrdbShared() {
		super("hrdb_shared");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.hr.service.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS,
			com.hr.service.tables.Employee.EMPLOYEE,
			com.hr.service.tables.LeavesApplied.LEAVES_APPLIED,
			com.hr.service.tables.LeavesLeft.LEAVES_LEFT,
			com.hr.service.tables.LeaveType.LEAVE_TYPE);
	}
}
