/**
 * This class is generated by jOOQ
 */
package com.hr.service.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeavesLeftRecord extends org.jooq.impl.UpdatableRecordImpl<com.hr.service.tables.records.LeavesLeftRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Byte> {

	private static final long serialVersionUID = -1684011322;

	/**
	 * Setter for <code>hrdb_shared.leaves_left.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_left.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_left.emp_id</code>.
	 */
	public void setEmpId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_left.emp_id</code>.
	 */
	public java.lang.Integer getEmpId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_left.leave_type</code>.
	 */
	public void setLeaveType(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_left.leave_type</code>.
	 */
	public java.lang.Integer getLeaveType() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_left.leaves_left</code>.
	 */
	public void setLeavesLeft(java.math.BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_left.leaves_left</code>.
	 */
	public java.math.BigDecimal getLeavesLeft() {
		return (java.math.BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_left.is_active</code>.
	 */
	public void setIsActive(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_left.is_active</code>.
	 */
	public java.lang.Byte getIsActive() {
		return (java.lang.Byte) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Byte> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.hr.service.tables.LeavesLeft.LEAVES_LEFT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.hr.service.tables.LeavesLeft.LEAVES_LEFT.EMP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.hr.service.tables.LeavesLeft.LEAVES_LEFT.LEAVE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field4() {
		return com.hr.service.tables.LeavesLeft.LEAVES_LEFT.LEAVES_LEFT_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return com.hr.service.tables.LeavesLeft.LEAVES_LEFT.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getEmpId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getLeaveType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value4() {
		return getLeavesLeft();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesLeftRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesLeftRecord value2(java.lang.Integer value) {
		setEmpId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesLeftRecord value3(java.lang.Integer value) {
		setLeaveType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesLeftRecord value4(java.math.BigDecimal value) {
		setLeavesLeft(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesLeftRecord value5(java.lang.Byte value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesLeftRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.math.BigDecimal value4, java.lang.Byte value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LeavesLeftRecord
	 */
	public LeavesLeftRecord() {
		super(com.hr.service.tables.LeavesLeft.LEAVES_LEFT);
	}

	/**
	 * Create a detached, initialised LeavesLeftRecord
	 */
	public LeavesLeftRecord(java.lang.Integer id, java.lang.Integer empId, java.lang.Integer leaveType, java.math.BigDecimal leavesLeft, java.lang.Byte isActive) {
		super(com.hr.service.tables.LeavesLeft.LEAVES_LEFT);

		setValue(0, id);
		setValue(1, empId);
		setValue(2, leaveType);
		setValue(3, leavesLeft);
		setValue(4, isActive);
	}
}
