CREATE TABLE religion(religion_id INT NOT NULL AUTO_INCREMENT, religion VARCHAR(30) NOT NULL, is_active TINYINT NOT NULL DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(religion_id));
CREATE TABLE race(race_id INT NOT NULL AUTO_INCREMENT, race VARCHAR(30) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(race_id));
CREATE TABLE nationality(nationality_id INT NOT NULL AUTO_INCREMENT, nationality VARCHAR(30) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(nationality_id));
CREATE TABLE blood_group(blood_group_id INT NOT NULL AUTO_INCREMENT, blood_group CHAR(5) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(blood_group_id));

CREATE TABLE emp_type(emp_type_id INT NOT NULL AUTO_INCREMENT, emp_type VARCHAR(30) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(emp_type_id));
CREATE TABLE working_type(working_type_id INT NOT NULL AUTO_INCREMENT, working_type VARCHAR(30) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(working_type_id));

CREATE TABLE company(company_id INT NOT NULL AUTO_INCREMENT, company VARCHAR(50) NOT NULL, description VARCHAR(100) NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(company_id));
CREATE TABLE department(department_id INT NOT NULL AUTO_INCREMENT, company_id INT NOT NULL, department VARCHAR(50) NOT NULL, description VARCHAR(100) NULL, is_active CHAR(1) DEFAULT '1',
PRIMARY KEY(department_id));
CREATE TABLE section(section_id INT NOT NULL AUTO_INCREMENT, company_id INT NOT NULL, department_id INT NOT NULL, section VARCHAR(50) NOT NULL, description VARCHAR(100) NULL,
is_active CHAR(1) DEFAULT '1', PRIMARY KEY(section_id));
CREATE TABLE location(location_id INT NOT NULL AUTO_INCREMENT, location VARCHAR(50) NOT NULL, description VARCHAR(100) NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(location_id));
CREATE TABLE designation(designation_id INT NOT NULL AUTO_INCREMENT,designation VARCHAR(50) NOT NULL, description VARCHAR(100) NULL, is_active CHAR(1) DEFAULT '1',
PRIMARY KEY(designation_id));

CREATE TABLE hris_user(user_id INT NOT NULL AUTO_INCREMENT, emp_number INT NOT NULL, user_type_id INT NOT NULL, display_name VARCHAR(30) NOT NULL, user_name VARCHAR(50) NOT NULL,
user_password VARCHAR(255) NOT NULL, is_active char(1) DEFAULT '1', expired CHAR(1) DEFAULT '0', created_by INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_by INT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(user_id));

CREATE TABLE employee(id INT NOT NULL AUTO_INCREMENT, card_number VARCHAR(15) NULL, gender_id INT NOT NULL, title_id INT NOT NULL, initials VARCHAR(15) NULL, first_name VARCHAR(30) NULL,
last_name VARCHAR(30) NULL, full_name VARCHAR(60) NOT NULL, nic_name VARCHAR(30) NULL,dob DATE NULL, nic VARCHAR(10) NULL, civil_status_id INT NOT NULL,
religion_id INT NOT NULL,race_id INT NOT NULL,national_id INT NOT NULL,blood_group INT NOT NULL,personal_email VARCHAR(50) NULL, distance_form_residence DOUBLE NOT NULL, collar_size INT NOT NULL,
emp_image VARCHAR(100) NULL,emp_cv VARCHAR(100) NULL,emp_status INT DEFAULT 1, created_by INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
updated_by INT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(id));


CREATE TABLE address_type (id INT NOT NULL AUTO_INCREMENT,addr_type VARCHAR(20) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(id));
CREATE TABLE address(id INT NOT NULL AUTO_INCREMENT, emp_number INT NOT NULL, type_id INT NOT NULL, house_no VARCHAR(10) NULL, street VARCHAR(50) NULL,
city VARCHAR(40) NULL, district VARCHAR(40) NULL, postal_code VARCHAR(10) NULL, is_active CHAR(1) DEFAULT '1', created_by INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
updated_by INT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(id));

CREATE TABLE contact_type( id INT NOT NULL AUTO_INCREMENT, cont_type VARCHAR(20) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(id));
CREATE TABLE contact(id INT NOT NULL AUTO_INCREMENT, emp_number INT NOT NULL, type_id INT NOT NULL, contact_number VARCHAR(14) NOT NULL, is_active VARCHAR(1) DEFAULT '1',
created_by INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_by INT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id));

CREATE TABLE edu_type( id INT NOT NULL AUTO_INCREMENT, edu_type_name VARCHAR(40) NOT NULL, is_active CHAR(1) DEFAULT '1', PRIMARY KEY(id));
CREATE TABLE education(id INT NOT NULL AUTO_INCREMENT, emp_number INT NOT NULL, venue VARCHAR(50) NULL, edu_year CHAR(4) null, edu_comment VARCHAR(100) NULL,
is_active CHAR(1) DEFAULT '1', created_by INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_by INT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id));
CREATE TABLE education_details(id INT NOT NULL AUTO_INCREMENT, edu_id INT NOT NULL, edu_subject VARCHAR(50) NOT NULL, result VARCHAR(20) NOT NULL,
is_active CHAR(1) DEFAULT '1', PRIMARY KEY(id));

CREATE TABLE bank_details(id INT NOT NULL AUTO_INCREMENT, emp_number INT NOT NULL, bank_name VARCHAR(30) NOT NULL, branch VARCHAR(20) NULL, bank_code CHAR(10) NULL,
branch_code CHAR(10) NULL, is_active CHAR(1) DEFAULT '1',created_by INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_by INT NULL, 
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(id));