/**
 * This class is generated by jOOQ
 */
package com.hr.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeavesApplied extends org.jooq.impl.TableImpl<com.hr.db.tables.records.LeavesAppliedRecord> {

	private static final long serialVersionUID = 1462935801;

	/**
	 * The singleton instance of <code>hrdb_shared.leaves_applied</code>
	 */
	public static final com.hr.db.tables.LeavesApplied LEAVES_APPLIED = new com.hr.db.tables.LeavesApplied();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hr.db.tables.records.LeavesAppliedRecord> getRecordType() {
		return com.hr.db.tables.records.LeavesAppliedRecord.class;
	}

	/**
	 * The column <code>hrdb_shared.leaves_applied.id</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.emp_id</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> EMP_ID = createField("emp_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.leave_type</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> LEAVE_TYPE = createField("leave_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.number_of_leaves</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> NUMBER_OF_LEAVES = createField("number_of_leaves", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.status</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.applied_on</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.sql.Timestamp> APPLIED_ON = createField("applied_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.reviewed_on</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.sql.Date> REVIEWED_ON = createField("reviewed_on", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.reviewed_by</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> REVIEWED_BY = createField("reviewed_by", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leaves_applied.is_active</code>.
	 */
	public final org.jooq.TableField<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Byte> IS_ACTIVE = createField("is_active", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>hrdb_shared.leaves_applied</code> table reference
	 */
	public LeavesApplied() {
		this("leaves_applied", null);
	}

	/**
	 * Create an aliased <code>hrdb_shared.leaves_applied</code> table reference
	 */
	public LeavesApplied(java.lang.String alias) {
		this(alias, com.hr.db.tables.LeavesApplied.LEAVES_APPLIED);
	}

	private LeavesApplied(java.lang.String alias, org.jooq.Table<com.hr.db.tables.records.LeavesAppliedRecord> aliased) {
		this(alias, aliased, null);
	}

	private LeavesApplied(java.lang.String alias, org.jooq.Table<com.hr.db.tables.records.LeavesAppliedRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hr.db.HrdbShared.HRDB_SHARED, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.hr.db.tables.records.LeavesAppliedRecord, java.lang.Integer> getIdentity() {
		return com.hr.db.Keys.IDENTITY_LEAVES_APPLIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.hr.db.tables.records.LeavesAppliedRecord> getPrimaryKey() {
		return com.hr.db.Keys.KEY_LEAVES_APPLIED_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.hr.db.tables.records.LeavesAppliedRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.hr.db.tables.records.LeavesAppliedRecord>>asList(com.hr.db.Keys.KEY_LEAVES_APPLIED_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.hr.db.tables.records.LeavesAppliedRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.hr.db.tables.records.LeavesAppliedRecord, ?>>asList(com.hr.db.Keys.LEAVES_APPLIED_IBFK_1, com.hr.db.Keys.LEAVES_APPLIED_IBFK_2, com.hr.db.Keys.LEAVES_APPLIED_IBFK_3, com.hr.db.Keys.LEAVES_APPLIED_IBFK_4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hr.db.tables.LeavesApplied as(java.lang.String alias) {
		return new com.hr.db.tables.LeavesApplied(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hr.db.tables.LeavesApplied rename(java.lang.String name) {
		return new com.hr.db.tables.LeavesApplied(name, null);
	}
}
