/**
 * This class is generated by jOOQ
 */
package com.hr.service;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>hrdb_shared</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.hr.service.tables.records.AppliedLeaveStatusRecord, java.lang.Integer> IDENTITY_APPLIED_LEAVE_STATUS = Identities0.IDENTITY_APPLIED_LEAVE_STATUS;
	public static final org.jooq.Identity<com.hr.service.tables.records.EmployeeRecord, java.lang.Integer> IDENTITY_EMPLOYEE = Identities0.IDENTITY_EMPLOYEE;
	public static final org.jooq.Identity<com.hr.service.tables.records.LeavesAppliedRecord, java.lang.Integer> IDENTITY_LEAVES_APPLIED = Identities0.IDENTITY_LEAVES_APPLIED;
	public static final org.jooq.Identity<com.hr.service.tables.records.LeavesLeftRecord, java.lang.Integer> IDENTITY_LEAVES_LEFT = Identities0.IDENTITY_LEAVES_LEFT;
	public static final org.jooq.Identity<com.hr.service.tables.records.LeaveTypeRecord, java.lang.Integer> IDENTITY_LEAVE_TYPE = Identities0.IDENTITY_LEAVE_TYPE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.hr.service.tables.records.AppliedLeaveStatusRecord> KEY_APPLIED_LEAVE_STATUS_PRIMARY = UniqueKeys0.KEY_APPLIED_LEAVE_STATUS_PRIMARY;
	public static final org.jooq.UniqueKey<com.hr.service.tables.records.EmployeeRecord> KEY_EMPLOYEE_PRIMARY = UniqueKeys0.KEY_EMPLOYEE_PRIMARY;
	public static final org.jooq.UniqueKey<com.hr.service.tables.records.LeavesAppliedRecord> KEY_LEAVES_APPLIED_PRIMARY = UniqueKeys0.KEY_LEAVES_APPLIED_PRIMARY;
	public static final org.jooq.UniqueKey<com.hr.service.tables.records.LeavesLeftRecord> KEY_LEAVES_LEFT_PRIMARY = UniqueKeys0.KEY_LEAVES_LEFT_PRIMARY;
	public static final org.jooq.UniqueKey<com.hr.service.tables.records.LeaveTypeRecord> KEY_LEAVE_TYPE_PRIMARY = UniqueKeys0.KEY_LEAVE_TYPE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.EmployeeRecord> LEAVES_APPLIED_IBFK_1 = ForeignKeys0.LEAVES_APPLIED_IBFK_1;
	public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.LeaveTypeRecord> LEAVES_APPLIED_IBFK_2 = ForeignKeys0.LEAVES_APPLIED_IBFK_2;
	public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.AppliedLeaveStatusRecord> LEAVES_APPLIED_IBFK_3 = ForeignKeys0.LEAVES_APPLIED_IBFK_3;
	public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.EmployeeRecord> LEAVES_APPLIED_IBFK_4 = ForeignKeys0.LEAVES_APPLIED_IBFK_4;
	public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesLeftRecord, com.hr.service.tables.records.EmployeeRecord> LEAVES_LEFT_IBFK_1 = ForeignKeys0.LEAVES_LEFT_IBFK_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.hr.service.tables.records.AppliedLeaveStatusRecord, java.lang.Integer> IDENTITY_APPLIED_LEAVE_STATUS = createIdentity(com.hr.service.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS, com.hr.service.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS.ID);
		public static org.jooq.Identity<com.hr.service.tables.records.EmployeeRecord, java.lang.Integer> IDENTITY_EMPLOYEE = createIdentity(com.hr.service.tables.Employee.EMPLOYEE, com.hr.service.tables.Employee.EMPLOYEE.ID);
		public static org.jooq.Identity<com.hr.service.tables.records.LeavesAppliedRecord, java.lang.Integer> IDENTITY_LEAVES_APPLIED = createIdentity(com.hr.service.tables.LeavesApplied.LEAVES_APPLIED, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED.ID);
		public static org.jooq.Identity<com.hr.service.tables.records.LeavesLeftRecord, java.lang.Integer> IDENTITY_LEAVES_LEFT = createIdentity(com.hr.service.tables.LeavesLeft.LEAVES_LEFT, com.hr.service.tables.LeavesLeft.LEAVES_LEFT.ID);
		public static org.jooq.Identity<com.hr.service.tables.records.LeaveTypeRecord, java.lang.Integer> IDENTITY_LEAVE_TYPE = createIdentity(com.hr.service.tables.LeaveType.LEAVE_TYPE, com.hr.service.tables.LeaveType.LEAVE_TYPE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.hr.service.tables.records.AppliedLeaveStatusRecord> KEY_APPLIED_LEAVE_STATUS_PRIMARY = createUniqueKey(com.hr.service.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS, com.hr.service.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS.ID);
		public static final org.jooq.UniqueKey<com.hr.service.tables.records.EmployeeRecord> KEY_EMPLOYEE_PRIMARY = createUniqueKey(com.hr.service.tables.Employee.EMPLOYEE, com.hr.service.tables.Employee.EMPLOYEE.ID);
		public static final org.jooq.UniqueKey<com.hr.service.tables.records.LeavesAppliedRecord> KEY_LEAVES_APPLIED_PRIMARY = createUniqueKey(com.hr.service.tables.LeavesApplied.LEAVES_APPLIED, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED.ID);
		public static final org.jooq.UniqueKey<com.hr.service.tables.records.LeavesLeftRecord> KEY_LEAVES_LEFT_PRIMARY = createUniqueKey(com.hr.service.tables.LeavesLeft.LEAVES_LEFT, com.hr.service.tables.LeavesLeft.LEAVES_LEFT.ID);
		public static final org.jooq.UniqueKey<com.hr.service.tables.records.LeaveTypeRecord> KEY_LEAVE_TYPE_PRIMARY = createUniqueKey(com.hr.service.tables.LeaveType.LEAVE_TYPE, com.hr.service.tables.LeaveType.LEAVE_TYPE.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.EmployeeRecord> LEAVES_APPLIED_IBFK_1 = createForeignKey(com.hr.service.Keys.KEY_EMPLOYEE_PRIMARY, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED.EMP_ID);
		public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.LeaveTypeRecord> LEAVES_APPLIED_IBFK_2 = createForeignKey(com.hr.service.Keys.KEY_LEAVE_TYPE_PRIMARY, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED.LEAVE_TYPE);
		public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.AppliedLeaveStatusRecord> LEAVES_APPLIED_IBFK_3 = createForeignKey(com.hr.service.Keys.KEY_APPLIED_LEAVE_STATUS_PRIMARY, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED.STATUS);
		public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesAppliedRecord, com.hr.service.tables.records.EmployeeRecord> LEAVES_APPLIED_IBFK_4 = createForeignKey(com.hr.service.Keys.KEY_EMPLOYEE_PRIMARY, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED, com.hr.service.tables.LeavesApplied.LEAVES_APPLIED.REVIEWED_BY);
		public static final org.jooq.ForeignKey<com.hr.service.tables.records.LeavesLeftRecord, com.hr.service.tables.records.EmployeeRecord> LEAVES_LEFT_IBFK_1 = createForeignKey(com.hr.service.Keys.KEY_EMPLOYEE_PRIMARY, com.hr.service.tables.LeavesLeft.LEAVES_LEFT, com.hr.service.tables.LeavesLeft.LEAVES_LEFT.EMP_ID);
	}
}
