/**
 * This class is generated by jOOQ
 */
package com.hr.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeavesAppliedRecord extends org.jooq.impl.UpdatableRecordImpl<com.hr.db.tables.records.LeavesAppliedRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Date, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = 1122396564;

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.emp_id</code>.
	 */
	public void setEmpId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.emp_id</code>.
	 */
	public java.lang.Integer getEmpId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.leave_type</code>.
	 */
	public void setLeaveType(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.leave_type</code>.
	 */
	public java.lang.Integer getLeaveType() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.number_of_leaves</code>.
	 */
	public void setNumberOfLeaves(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.number_of_leaves</code>.
	 */
	public java.lang.Integer getNumberOfLeaves() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.status</code>.
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.status</code>.
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.applied_on</code>.
	 */
	public void setAppliedOn(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.applied_on</code>.
	 */
	public java.sql.Timestamp getAppliedOn() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.reviewed_on</code>.
	 */
	public void setReviewedOn(java.sql.Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.reviewed_on</code>.
	 */
	public java.sql.Date getReviewedOn() {
		return (java.sql.Date) getValue(6);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.reviewed_by</code>.
	 */
	public void setReviewedBy(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.reviewed_by</code>.
	 */
	public java.lang.Integer getReviewedBy() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>hrdb_shared.leaves_applied.is_active</code>.
	 */
	public void setIsActive(java.lang.Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>hrdb_shared.leaves_applied.is_active</code>.
	 */
	public java.lang.Byte getIsActive() {
		return (java.lang.Byte) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Date, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Date, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.EMP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.LEAVE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.NUMBER_OF_LEAVES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.APPLIED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field7() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.REVIEWED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.REVIEWED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field9() {
		return com.hr.db.tables.LeavesApplied.LEAVES_APPLIED.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getEmpId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getLeaveType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getNumberOfLeaves();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getAppliedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value7() {
		return getReviewedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getReviewedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value9() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value2(java.lang.Integer value) {
		setEmpId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value3(java.lang.Integer value) {
		setLeaveType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value4(java.lang.Integer value) {
		setNumberOfLeaves(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value5(java.lang.Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value6(java.sql.Timestamp value) {
		setAppliedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value7(java.sql.Date value) {
		setReviewedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value8(java.lang.Integer value) {
		setReviewedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord value9(java.lang.Byte value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeavesAppliedRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.sql.Timestamp value6, java.sql.Date value7, java.lang.Integer value8, java.lang.Byte value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LeavesAppliedRecord
	 */
	public LeavesAppliedRecord() {
		super(com.hr.db.tables.LeavesApplied.LEAVES_APPLIED);
	}

	/**
	 * Create a detached, initialised LeavesAppliedRecord
	 */
	public LeavesAppliedRecord(java.lang.Integer id, java.lang.Integer empId, java.lang.Integer leaveType, java.lang.Integer numberOfLeaves, java.lang.Integer status, java.sql.Timestamp appliedOn, java.sql.Date reviewedOn, java.lang.Integer reviewedBy, java.lang.Byte isActive) {
		super(com.hr.db.tables.LeavesApplied.LEAVES_APPLIED);

		setValue(0, id);
		setValue(1, empId);
		setValue(2, leaveType);
		setValue(3, numberOfLeaves);
		setValue(4, status);
		setValue(5, appliedOn);
		setValue(6, reviewedOn);
		setValue(7, reviewedBy);
		setValue(8, isActive);
	}
}
