/**
 * This class is generated by jOOQ
 */
package com.hr.service.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaveType extends org.jooq.impl.TableImpl<com.hr.service.tables.records.LeaveTypeRecord> {

	private static final long serialVersionUID = -156332894;

	/**
	 * The singleton instance of <code>hrdb_shared.leave_type</code>
	 */
	public static final com.hr.service.tables.LeaveType LEAVE_TYPE = new com.hr.service.tables.LeaveType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hr.service.tables.records.LeaveTypeRecord> getRecordType() {
		return com.hr.service.tables.records.LeaveTypeRecord.class;
	}

	/**
	 * The column <code>hrdb_shared.leave_type.id</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.LeaveTypeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leave_type.type</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.LeaveTypeRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.leave_type.is_active</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.LeaveTypeRecord, java.lang.Byte> IS_ACTIVE = createField("is_active", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>hrdb_shared.leave_type</code> table reference
	 */
	public LeaveType() {
		this("leave_type", null);
	}

	/**
	 * Create an aliased <code>hrdb_shared.leave_type</code> table reference
	 */
	public LeaveType(java.lang.String alias) {
		this(alias, com.hr.service.tables.LeaveType.LEAVE_TYPE);
	}

	private LeaveType(java.lang.String alias, org.jooq.Table<com.hr.service.tables.records.LeaveTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private LeaveType(java.lang.String alias, org.jooq.Table<com.hr.service.tables.records.LeaveTypeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hr.service.HrdbShared.HRDB_SHARED, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.hr.service.tables.records.LeaveTypeRecord, java.lang.Integer> getIdentity() {
		return com.hr.service.Keys.IDENTITY_LEAVE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.hr.service.tables.records.LeaveTypeRecord> getPrimaryKey() {
		return com.hr.service.Keys.KEY_LEAVE_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.hr.service.tables.records.LeaveTypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.hr.service.tables.records.LeaveTypeRecord>>asList(com.hr.service.Keys.KEY_LEAVE_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hr.service.tables.LeaveType as(java.lang.String alias) {
		return new com.hr.service.tables.LeaveType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hr.service.tables.LeaveType rename(java.lang.String name) {
		return new com.hr.service.tables.LeaveType(name, null);
	}
}
