/**
 * This class is generated by jOOQ
 */
package com.hr.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in hrdb_shared
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table hrdb_shared.applied_leave_status
	 */
	public static final com.hr.db.tables.AppliedLeaveStatus APPLIED_LEAVE_STATUS = com.hr.db.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS;

	/**
	 * The table hrdb_shared.employee
	 */
	public static final com.hr.db.tables.Employee EMPLOYEE = com.hr.db.tables.Employee.EMPLOYEE;

	/**
	 * The table hrdb_shared.leaves_applied
	 */
	public static final com.hr.db.tables.LeavesApplied LEAVES_APPLIED = com.hr.db.tables.LeavesApplied.LEAVES_APPLIED;

	/**
	 * The table hrdb_shared.leaves_left
	 */
	public static final com.hr.db.tables.LeavesLeft LEAVES_LEFT = com.hr.db.tables.LeavesLeft.LEAVES_LEFT;

	/**
	 * The table hrdb_shared.leave_type
	 */
	public static final com.hr.db.tables.LeaveType LEAVE_TYPE = com.hr.db.tables.LeaveType.LEAVE_TYPE;
}
