/**
 * This class is generated by jOOQ
 */
package com.hr.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppliedLeaveStatusRecord extends org.jooq.impl.UpdatableRecordImpl<com.hr.db.tables.records.AppliedLeaveStatusRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Byte> {

	private static final long serialVersionUID = -903116322;

	/**
	 * Setter for <code>hrdb_shared.applied_leave_status.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hrdb_shared.applied_leave_status.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hrdb_shared.applied_leave_status.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hrdb_shared.applied_leave_status.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>hrdb_shared.applied_leave_status.is_active</code>.
	 */
	public void setIsActive(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hrdb_shared.applied_leave_status.is_active</code>.
	 */
	public java.lang.Byte getIsActive() {
		return (java.lang.Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Byte> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.hr.db.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.hr.db.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return com.hr.db.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppliedLeaveStatusRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppliedLeaveStatusRecord value2(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppliedLeaveStatusRecord value3(java.lang.Byte value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppliedLeaveStatusRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Byte value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppliedLeaveStatusRecord
	 */
	public AppliedLeaveStatusRecord() {
		super(com.hr.db.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS);
	}

	/**
	 * Create a detached, initialised AppliedLeaveStatusRecord
	 */
	public AppliedLeaveStatusRecord(java.lang.Integer id, java.lang.String status, java.lang.Byte isActive) {
		super(com.hr.db.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS);

		setValue(0, id);
		setValue(1, status);
		setValue(2, isActive);
	}
}
