/**
 * This class is generated by jOOQ
 */
package com.hr.service.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppliedLeaveStatus extends org.jooq.impl.TableImpl<com.hr.service.tables.records.AppliedLeaveStatusRecord> {

	private static final long serialVersionUID = -1103941200;

	/**
	 * The singleton instance of <code>hrdb_shared.applied_leave_status</code>
	 */
	public static final com.hr.service.tables.AppliedLeaveStatus APPLIED_LEAVE_STATUS = new com.hr.service.tables.AppliedLeaveStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hr.service.tables.records.AppliedLeaveStatusRecord> getRecordType() {
		return com.hr.service.tables.records.AppliedLeaveStatusRecord.class;
	}

	/**
	 * The column <code>hrdb_shared.applied_leave_status.id</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.AppliedLeaveStatusRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.applied_leave_status.status</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.AppliedLeaveStatusRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.applied_leave_status.is_active</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.AppliedLeaveStatusRecord, java.lang.Byte> IS_ACTIVE = createField("is_active", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>hrdb_shared.applied_leave_status</code> table reference
	 */
	public AppliedLeaveStatus() {
		this("applied_leave_status", null);
	}

	/**
	 * Create an aliased <code>hrdb_shared.applied_leave_status</code> table reference
	 */
	public AppliedLeaveStatus(java.lang.String alias) {
		this(alias, com.hr.service.tables.AppliedLeaveStatus.APPLIED_LEAVE_STATUS);
	}

	private AppliedLeaveStatus(java.lang.String alias, org.jooq.Table<com.hr.service.tables.records.AppliedLeaveStatusRecord> aliased) {
		this(alias, aliased, null);
	}

	private AppliedLeaveStatus(java.lang.String alias, org.jooq.Table<com.hr.service.tables.records.AppliedLeaveStatusRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hr.service.HrdbShared.HRDB_SHARED, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.hr.service.tables.records.AppliedLeaveStatusRecord, java.lang.Integer> getIdentity() {
		return com.hr.service.Keys.IDENTITY_APPLIED_LEAVE_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.hr.service.tables.records.AppliedLeaveStatusRecord> getPrimaryKey() {
		return com.hr.service.Keys.KEY_APPLIED_LEAVE_STATUS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.hr.service.tables.records.AppliedLeaveStatusRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.hr.service.tables.records.AppliedLeaveStatusRecord>>asList(com.hr.service.Keys.KEY_APPLIED_LEAVE_STATUS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hr.service.tables.AppliedLeaveStatus as(java.lang.String alias) {
		return new com.hr.service.tables.AppliedLeaveStatus(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hr.service.tables.AppliedLeaveStatus rename(java.lang.String name) {
		return new com.hr.service.tables.AppliedLeaveStatus(name, null);
	}
}
