/**
 * This class is generated by jOOQ
 */
package com.hr.service.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends org.jooq.impl.TableImpl<com.hr.service.tables.records.EmployeeRecord> {

	private static final long serialVersionUID = -1114365013;

	/**
	 * The singleton instance of <code>hrdb_shared.employee</code>
	 */
	public static final com.hr.service.tables.Employee EMPLOYEE = new com.hr.service.tables.Employee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.hr.service.tables.records.EmployeeRecord> getRecordType() {
		return com.hr.service.tables.records.EmployeeRecord.class;
	}

	/**
	 * The column <code>hrdb_shared.employee.id</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.EmployeeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hrdb_shared.employee.first_name</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.EmployeeRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>hrdb_shared.employee.last_name</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.EmployeeRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>hrdb_shared.employee.full_name</code>.
	 */
	public final org.jooq.TableField<com.hr.service.tables.records.EmployeeRecord, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR.length(60).nullable(false), this, "");

	/**
	 * Create a <code>hrdb_shared.employee</code> table reference
	 */
	public Employee() {
		this("employee", null);
	}

	/**
	 * Create an aliased <code>hrdb_shared.employee</code> table reference
	 */
	public Employee(java.lang.String alias) {
		this(alias, com.hr.service.tables.Employee.EMPLOYEE);
	}

	private Employee(java.lang.String alias, org.jooq.Table<com.hr.service.tables.records.EmployeeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Employee(java.lang.String alias, org.jooq.Table<com.hr.service.tables.records.EmployeeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.hr.service.HrdbShared.HRDB_SHARED, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.hr.service.tables.records.EmployeeRecord, java.lang.Integer> getIdentity() {
		return com.hr.service.Keys.IDENTITY_EMPLOYEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.hr.service.tables.records.EmployeeRecord> getPrimaryKey() {
		return com.hr.service.Keys.KEY_EMPLOYEE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.hr.service.tables.records.EmployeeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.hr.service.tables.records.EmployeeRecord>>asList(com.hr.service.Keys.KEY_EMPLOYEE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.hr.service.tables.Employee as(java.lang.String alias) {
		return new com.hr.service.tables.Employee(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.hr.service.tables.Employee rename(java.lang.String name) {
		return new com.hr.service.tables.Employee(name, null);
	}
}
